kCombatEquipmentSentryCost = kShotgunCost
kCombatEquipmentSentryResearchCost = kShotgunTechResearchCost
kCombatEquipmentSentryResearchTime = kShotgunTechResearchTime
kCombatEquipmentSentryPointValue = 10